name: vscode_material_icon_theme
description: "A Flutter package that ports the popular vscode-material-icon-theme to Flutter"
version: 5.26.0
homepage: https://github.com/BoxMeApp/vscode_material_icon_theme

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  vector_graphics_compiler: ^1.1.17


flutter:
  assets:
    - assets/icons/

