import 'language_id.g.dart';

/// Maps exact filenames (without extension) to VSCode Language IDs
const Map<String, VSCodeLanguageId> filenameToLanguageId = {
  // Git files
  'gitignore': VSCodeLanguageId.ignore,
  '.gitignore': VSCodeLanguageId.ignore,
  'gitattributes': VSCodeLanguageId.ignore,
  '.gitattributes': VSCodeLanguageId.ignore,
  'git_commit_editmsg': VSCodeLanguageId.git_commit,
  'git_rebase_todo': VSCodeLanguageId.git_rebase,

  // Build and config files
  'dockerfile': VSCodeLanguageId.dockerfile,
  'docker-compose.yml': VSCodeLanguageId.dockercompose,
  'docker-compose.yaml': VSCodeLanguageId.dockercompose,
  'compose.yml': VSCodeLanguageId.dockercompose,
  'compose.yaml': VSCodeLanguageId.dockercompose,
  'makefile': VSCodeLanguageId.makefile,
  'gnumakefile': VSCodeLanguageId.makefile,
  'makefile.am': VSCodeLanguageId.makefile,
  'makefile.in': VSCodeLanguageId.makefile,
  '.editorconfig': VSCodeLanguageId.editorconfig,
  'jenkinsfile': VSCodeLanguageId.groovy,

  // Ruby files
  'vagrantfile': VSCodeLanguageId.ruby,
  'rakefile': VSCodeLanguageId.ruby,
  'gemfile': VSCodeLanguageId.ruby,
  'podfile': VSCodeLanguageId.ruby,
  'brewfile': VSCodeLanguageId.ruby,
  'fastfile': VSCodeLanguageId.ruby,
  'appfile': VSCodeLanguageId.ruby,
  'deliverfile': VSCodeLanguageId.ruby,
  'matchfile': VSCodeLanguageId.ruby,
  'scanfile': VSCodeLanguageId.ruby,
  'snapfile': VSCodeLanguageId.ruby,
  'gymfile': VSCodeLanguageId.ruby,

  // Shell config files
  '.bashrc': VSCodeLanguageId.shellscript,
  '.zshrc': VSCodeLanguageId.shellscript,
  '.bash_profile': VSCodeLanguageId.shellscript,
  '.zsh_profile': VSCodeLanguageId.shellscript,
  '.profile': VSCodeLanguageId.shellscript,
  '.bash_aliases': VSCodeLanguageId.shellscript,
  '.zsh_aliases': VSCodeLanguageId.shellscript,

  // Environment files
  '.env': VSCodeLanguageId.properties,
  '.env.local': VSCodeLanguageId.properties,
  '.env.development': VSCodeLanguageId.properties,
  '.env.production': VSCodeLanguageId.properties,
  '.env.test': VSCodeLanguageId.properties,

  // Documentation
  'readme': VSCodeLanguageId.markdown,
  'readme.txt': VSCodeLanguageId.markdown,
  'changelog': VSCodeLanguageId.markdown,
  'changelog.txt': VSCodeLanguageId.markdown,
  'license': VSCodeLanguageId.plaintext,
  'licence': VSCodeLanguageId.plaintext,
  'authors': VSCodeLanguageId.plaintext,
  'contributors': VSCodeLanguageId.plaintext,

  // SSH config
  'ssh_config': VSCodeLanguageId.ssh_config,
  'sshd_config': VSCodeLanguageId.ssh_config,
  '.ssh/config': VSCodeLanguageId.ssh_config,

  // Hosts file
  'hosts': VSCodeLanguageId.hosts,
};

/// Maps file extensions to VSCode Language IDs
const Map<String, VSCodeLanguageId> extensionToLanguageId = {
  // Programming languages
  '.py': VSCodeLanguageId.python,
  '.pyw': VSCodeLanguageId.python,
  '.pyi': VSCodeLanguageId.python,
  '.mojo': VSCodeLanguageId.mojo,
  '.js': VSCodeLanguageId.javascript,
  '.mjs': VSCodeLanguageId.javascript,
  '.cjs': VSCodeLanguageId.javascript,
  '.ts': VSCodeLanguageId.typescript,
  '.mts': VSCodeLanguageId.typescript,
  '.cts': VSCodeLanguageId.typescript,
  '.jsx': VSCodeLanguageId.javascriptreact,
  '.tsx': VSCodeLanguageId.typescriptreact,
  '.ets': VSCodeLanguageId.ets,
  '.java': VSCodeLanguageId.java,
  '.scala': VSCodeLanguageId.scala,
  '.sc': VSCodeLanguageId.scala,
  '.dart': VSCodeLanguageId.dart,
  '.go': VSCodeLanguageId.go,
  '.rs': VSCodeLanguageId.rust,
  '.c': VSCodeLanguageId.c,
  '.cpp': VSCodeLanguageId.cpp,
  '.cc': VSCodeLanguageId.cpp,
  '.cxx': VSCodeLanguageId.cpp,
  '.c++': VSCodeLanguageId.cpp,
  '.h': VSCodeLanguageId.cpp,
  '.hpp': VSCodeLanguageId.cpp,
  '.hh': VSCodeLanguageId.cpp,
  '.hxx': VSCodeLanguageId.cpp,
  '.h++': VSCodeLanguageId.cpp,
  '.m': VSCodeLanguageId.objective_c,
  '.mm': VSCodeLanguageId.objective_cpp,
  '.c3': VSCodeLanguageId.c3,
  '.cs': VSCodeLanguageId.csharp,
  '.fs': VSCodeLanguageId.fsharp,
  '.fsi': VSCodeLanguageId.fsharp,
  '.fsx': VSCodeLanguageId.fsharp,
  '.vb': VSCodeLanguageId.vb,
  '.swift': VSCodeLanguageId.swift,
  '.php': VSCodeLanguageId.php,
  '.php3': VSCodeLanguageId.php,
  '.php4': VSCodeLanguageId.php,
  '.php5': VSCodeLanguageId.php,
  '.phtml': VSCodeLanguageId.php,
  '.hack': VSCodeLanguageId.hack,
  '.rb': VSCodeLanguageId.ruby,
  '.rbw': VSCodeLanguageId.ruby,
  '.slim': VSCodeLanguageId.slim,
  '.perl': VSCodeLanguageId.perl,
  '.pl': VSCodeLanguageId.perl,
  '.pm': VSCodeLanguageId.perl,
  '.p6': VSCodeLanguageId.perl6,
  '.pl6': VSCodeLanguageId.perl6,
  '.pm6': VSCodeLanguageId.perl6,
  '.hx': VSCodeLanguageId.haxe,
  '.hxml': VSCodeLanguageId.hxml,
  '.ex': VSCodeLanguageId.elixir,
  '.exs': VSCodeLanguageId.elixir,
  '.erl': VSCodeLanguageId.erlang,
  '.hrl': VSCodeLanguageId.erlang,
  '.ls': VSCodeLanguageId.livescript,
  '.coffee': VSCodeLanguageId.coffeescript,
  '.jl': VSCodeLanguageId.julia,
  '.elm': VSCodeLanguageId.elm,
  '.purs': VSCodeLanguageId.purescript,
  '.hs': VSCodeLanguageId.haskell,
  '.lhs': VSCodeLanguageId.haskell,
  '.dhall': VSCodeLanguageId.dhall,
  '.cabal': VSCodeLanguageId.cabal,
  '.nix': VSCodeLanguageId.nix,
  '.clj': VSCodeLanguageId.clojure,
  '.cljs': VSCodeLanguageId.clojure,
  '.cljc': VSCodeLanguageId.clojure,
  '.edn': VSCodeLanguageId.clojure,
  '.groovy': VSCodeLanguageId.groovy,
  '.gvy': VSCodeLanguageId.groovy,
  '.gradle': VSCodeLanguageId.groovy,
  '.lua': VSCodeLanguageId.lua,
  '.luau': VSCodeLanguageId.luau,
  '.r': VSCodeLanguageId.r,
  '.rdata': VSCodeLanguageId.r,
  '.rds': VSCodeLanguageId.r,
  '.rnw': VSCodeLanguageId.rsweave,
  '.nim': VSCodeLanguageId.nim,
  '.nimble': VSCodeLanguageId.nimble,
  '.ml': VSCodeLanguageId.sml,
  '.mli': VSCodeLanguageId.sml,
  '.re': VSCodeLanguageId.reason,
  '.rei': VSCodeLanguageId.reason,
  '.res': VSCodeLanguageId.rescript,
  '.resi': VSCodeLanguageId.rescript,
  '.v': VSCodeLanguageId.v,
  '.sas': VSCodeLanguageId.sas,
  '.au3': VSCodeLanguageId.autoit,
  '.ahk': VSCodeLanguageId.autoit,
  '.ahk2': VSCodeLanguageId.ahk2,
  '.applescript': VSCodeLanguageId.applescript,
  '.scpt': VSCodeLanguageId.applescript,
  '.cake': VSCodeLanguageId.cake,
  '.pawn': VSCodeLanguageId.pawn,
  '.pro': VSCodeLanguageId.prolog,
  '.prolog': VSCodeLanguageId.prolog,
  '.gd': VSCodeLanguageId.gdscript,
  '.gdshader': VSCodeLanguageId.gdshader,
  '.tres': VSCodeLanguageId.gdresource,
  '.tscn': VSCodeLanguageId.gdresource,
  '.vim': VSCodeLanguageId.viml,
  '.pp': VSCodeLanguageId.puppet,
  '.grain': VSCodeLanguageId.grain,
  '.lol': VSCodeLanguageId.lolcode,
  '.idr': VSCodeLanguageId.idris,
  '.wl': VSCodeLanguageId.wolfram,
  '.nb': VSCodeLanguageId.wolfram,
  '.cdc': VSCodeLanguageId.cadence,
  '.huff': VSCodeLanguageId.huff,
  '.cds': VSCodeLanguageId.cds,
  '.slint': VSCodeLanguageId.slint,
  '.bean': VSCodeLanguageId.beancount,
  '.beancount': VSCodeLanguageId.beancount,
  '.gp': VSCodeLanguageId.gnuplot,
  '.gnuplot': VSCodeLanguageId.gnuplot,

  // Web technologies
  '.html': VSCodeLanguageId.html,
  '.htm': VSCodeLanguageId.html,
  '.css': VSCodeLanguageId.css,
  '.scss': VSCodeLanguageId.scss,
  '.sass': VSCodeLanguageId.sass,
  '.less': VSCodeLanguageId.less,
  '.styl': VSCodeLanguageId.stylus,
  '.stylus': VSCodeLanguageId.stylus,
  '.postcss': VSCodeLanguageId.postcss,
  '.st': VSCodeLanguageId.stylable,
  '.vue': VSCodeLanguageId.vue,
  '.svelte': VSCodeLanguageId.svelte,
  '.handlebars': VSCodeLanguageId.handlebars,
  '.hbs': VSCodeLanguageId.handlebars,
  '.twig': VSCodeLanguageId.twig,
  '.nunjucks': VSCodeLanguageId.nunjucks,
  '.njk': VSCodeLanguageId.nunjucks,
  '.pug': VSCodeLanguageId.pug,
  '.jade': VSCodeLanguageId.pug,
  '.haml': VSCodeLanguageId.haml,
  '.mjml': VSCodeLanguageId.mjml,
  '.riot': VSCodeLanguageId.riot,
  '.ejs': VSCodeLanguageId.html,
  '.jinja': VSCodeLanguageId.jinja,
  '.jinja2': VSCodeLanguageId.jinja,
  '.j2': VSCodeLanguageId.jinja,
  '.razor': VSCodeLanguageId.razor,

  // Data formats
  '.json': VSCodeLanguageId.json,
  '.jsonc': VSCodeLanguageId.jsonc,
  '.json5': VSCodeLanguageId.json5,
  '.hjson': VSCodeLanguageId.hjson,
  '.yaml': VSCodeLanguageId.yaml,
  '.yml': VSCodeLanguageId.yaml,
  '.toml': VSCodeLanguageId.toml,
  '.xml': VSCodeLanguageId.xml,
  '.xsd': VSCodeLanguageId.xml,
  '.xsl': VSCodeLanguageId.xml,
  '.xslt': VSCodeLanguageId.xml,
  '.xquery': VSCodeLanguageId.xquery,
  '.xq': VSCodeLanguageId.xquery,
  '.csv': VSCodeLanguageId.csv,
  '.tsv': VSCodeLanguageId.tsv,
  '.psv': VSCodeLanguageId.psv,
  '.ini': VSCodeLanguageId.ini,
  '.cfg': VSCodeLanguageId.ini,
  '.conf': VSCodeLanguageId.ini,
  '.properties': VSCodeLanguageId.properties,
  '.proto': VSCodeLanguageId.proto,
  '.graphql': VSCodeLanguageId.graphql,
  '.gql': VSCodeLanguageId.graphql,

  // Shell and scripts
  '.sh': VSCodeLanguageId.shellscript,
  '.bash': VSCodeLanguageId.shellscript,
  '.zsh': VSCodeLanguageId.shellscript,
  '.fish': VSCodeLanguageId.shellscript,
  '.ksh': VSCodeLanguageId.shellscript,
  '.csh': VSCodeLanguageId.shellscript,
  '.tcsh': VSCodeLanguageId.shellscript,
  '.bat': VSCodeLanguageId.bat,
  '.cmd': VSCodeLanguageId.bat,
  '.ps1': VSCodeLanguageId.powershell,
  '.psm1': VSCodeLanguageId.powershell,
  '.psd1': VSCodeLanguageId.powershell,
  '.awk': VSCodeLanguageId.awk,

  // Documentation
  '.md': VSCodeLanguageId.markdown,
  '.markdown': VSCodeLanguageId.markdown,
  '.mdown': VSCodeLanguageId.markdown,
  '.mkd': VSCodeLanguageId.markdown,
  '.mkdn': VSCodeLanguageId.markdown,
  '.mdoc': VSCodeLanguageId.markdoc,
  '.tex': VSCodeLanguageId.tex,
  '.latex': VSCodeLanguageId.latex,
  '.cls': VSCodeLanguageId.latex_class,
  '.sty': VSCodeLanguageId.latex_package,
  '.dtx': VSCodeLanguageId.doctex,
  '.ins': VSCodeLanguageId.doctex_installer,
  '.bib': VSCodeLanguageId.bibtex,
  '.bst': VSCodeLanguageId.bibtex_style,
  '.asciidoc': VSCodeLanguageId.plaintext,
  '.adoc': VSCodeLanguageId.plaintext,
  '.rst': VSCodeLanguageId.plaintext,
  '.txt': VSCodeLanguageId.plaintext,

  // Specialized formats
  '.sql': VSCodeLanguageId.sql,
  '.kql': VSCodeLanguageId.kql,
  '.diff': VSCodeLanguageId.diff,
  '.patch': VSCodeLanguageId.diff,
  '.log': VSCodeLanguageId.log,
  '.svg': VSCodeLanguageId.svg,
  '.pdf': VSCodeLanguageId.pdf,
  '.ipynb': VSCodeLanguageId.jupyter,
  '.sol': VSCodeLanguageId.solidity,
  '.tf': VSCodeLanguageId.terraform,
  '.tfvars': VSCodeLanguageId.terraform,
  '.hcl': VSCodeLanguageId.hcl,
  '.yang': VSCodeLanguageId.yang,
  '.feature': VSCodeLanguageId.cucumber,
  '.robot': VSCodeLanguageId.robotframework,
  '.apib': VSCodeLanguageId.apiblueprint,
  '.mcfunction': VSCodeLanguageId.mcfunction,
  '.otne': VSCodeLanguageId.otne,
  '.twee': VSCodeLanguageId.twee3,
  '.pgn': VSCodeLanguageId.pgn,
  '.gmi': VSCodeLanguageId.gemini,
  '.gemini': VSCodeLanguageId.gemini,
  '.tree': VSCodeLanguageId.tree,
  '.shader': VSCodeLanguageId.shaderlab,
  '.compute': VSCodeLanguageId.shaderlab,
  '.hlsl': VSCodeLanguageId.hlsl,
  '.glsl': VSCodeLanguageId.glsl,
  '.vert': VSCodeLanguageId.glsl,
  '.frag': VSCodeLanguageId.glsl,
  '.geom': VSCodeLanguageId.glsl,
  '.tesc': VSCodeLanguageId.glsl,
  '.tese': VSCodeLanguageId.glsl,
  '.comp': VSCodeLanguageId.glsl,
  '.wgsl': VSCodeLanguageId.wgsl,
  '.mat': VSCodeLanguageId.matlab,
  '.matlab': VSCodeLanguageId.matlab,
  '.pde': VSCodeLanguageId.processing,
  '.apex': VSCodeLanguageId.apex,
  '.trigger': VSCodeLanguageId.apex,
  '.cfml': VSCodeLanguageId.lang_cfml,
  '.cfc': VSCodeLanguageId.lang_cfml,
  '.cfm': VSCodeLanguageId.lang_cfml,
  '.blink': VSCodeLanguageId.blink,
  '.requirements': VSCodeLanguageId.pip_requirements,
  '.requirements.txt': VSCodeLanguageId.pip_requirements,
};

final allLanguageIdsExtension = extensionToLanguageId.keys.toSet();
